// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartStorage_API.Model.Context;

#nullable disable

namespace SmartStorage_API.Migrations
{
    [DbContext(typeof(SmartStorageContext))]
    [Migration("20260120181631_UpdateUserTable")]
    partial class UpdateUserTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartStorage_Shared.Model.Employee", b =>
                {
                    b.Property<int>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpId"));

                    b.Property<string>("EmpCpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime>("EmpDateRegister")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmpName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmpRg")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("EmpId");

                    b.ToTable("Employee", "dbo");
                });

            modelBuilder.Entity("SmartStorage_Shared.Model.Enter", b =>
                {
                    b.Property<int>("EntId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntId"));

                    b.Property<DateTime>("EntDateEnter")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EntPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EntProId")
                        .HasColumnType("int");

                    b.Property<int>("EntQntd")
                        .HasColumnType("int");

                    b.Property<int>("EntSheId")
                        .HasColumnType("int");

                    b.HasKey("EntId");

                    b.HasIndex(new[] { "EntProId" }, "IX_Enter_productId");

                    b.HasIndex(new[] { "EntSheId" }, "IX_Enter_shelfId");

                    b.ToTable("Enter", "dbo");
                });

            modelBuilder.Entity("SmartStorage_Shared.Model.Product", b =>
                {
                    b.Property<int>("ProId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProId"));

                    b.Property<DateTime>("ProDateRegister")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProDescription")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("ProEmpId")
                        .HasColumnType("int");

                    b.Property<byte[]>("ProImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ProName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProQntd")
                        .HasColumnType("int");

                    b.HasKey("ProId");

                    b.HasIndex(new[] { "ProEmpId" }, "IX_Product_employeeId");

                    b.ToTable("Product", "dbo");
                });

            modelBuilder.Entity("SmartStorage_Shared.Model.Sale", b =>
                {
                    b.Property<int>("SalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalId"));

                    b.Property<DateTime>("SalDateSale")
                        .HasColumnType("datetime2");

                    b.Property<int>("SalEntId")
                        .HasColumnType("int");

                    b.Property<int>("SalQntd")
                        .HasColumnType("int");

                    b.HasKey("SalId");

                    b.HasIndex(new[] { "SalEntId" }, "IX_Sale_enterId");

                    b.ToTable("Sale", "dbo");
                });

            modelBuilder.Entity("SmartStorage_Shared.Model.Shelf", b =>
                {
                    b.Property<int>("SheId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SheId"));

                    b.Property<DateTime>("SheDataRegister")
                        .HasColumnType("datetime2");

                    b.Property<string>("SheName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SheId");

                    b.ToTable("Shelf", "dbo");
                });

            modelBuilder.Entity("SmartStorage_Shared.Model.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("full_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(130)
                        .HasColumnType("nvarchar(130)")
                        .HasColumnName("password");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("refresh_token_expiry_time");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("UQ_users_user_name");

                    b.ToTable("users", "dbo");
                });

            modelBuilder.Entity("SmartStorage_Shared.Model.Enter", b =>
                {
                    b.HasOne("SmartStorage_Shared.Model.Product", "Product")
                        .WithMany("Enters")
                        .HasForeignKey("EntProId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartStorage_Shared.Model.Shelf", "Shelf")
                        .WithMany("Enters")
                        .HasForeignKey("EntSheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Shelf");
                });

            modelBuilder.Entity("SmartStorage_Shared.Model.Product", b =>
                {
                    b.HasOne("SmartStorage_Shared.Model.Employee", "Employee")
                        .WithMany("Products")
                        .HasForeignKey("ProEmpId");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SmartStorage_Shared.Model.Sale", b =>
                {
                    b.HasOne("SmartStorage_Shared.Model.Enter", "Enter")
                        .WithMany("Sales")
                        .HasForeignKey("SalEntId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enter");
                });

            modelBuilder.Entity("SmartStorage_Shared.Model.Employee", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("SmartStorage_Shared.Model.Enter", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("SmartStorage_Shared.Model.Product", b =>
                {
                    b.Navigation("Enters");
                });

            modelBuilder.Entity("SmartStorage_Shared.Model.Shelf", b =>
                {
                    b.Navigation("Enters");
                });
#pragma warning restore 612, 618
        }
    }
}
